//@prepros-append functions
//@prepros-append burger
//@prepros-append submenu
//@prepros-append cards
//@prepros-append tabs
//@prepros-append validation-form
//@prepros-append typing-text
//@prepros-append glowing
//@prepros-append popup
//@prepros-append logos